# Generated by Django 3.2.9 on 2022-01-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('apply_date', models.DateTimeField(null=True)),
                ('destroy_date', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='/')),
                ('creation_date', models.DateTimeField(null=True)),
                ('deletion_date', models.DateTimeField(null=True)),
                ('is_useable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TerraformParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('BOOL', 'Boolean'), ('STRING', 'String'), ('NUMBER', 'Number'), ('LIST', 'List'), ('TOUPLE', 'Tuple'), ('MAP', 'Map'), ('OBJECT', 'Object'), ('NULL', 'Null')], default='STRING', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformParamToModuleAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terraform_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformmodule')),
                ('terraform_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformparam')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('deployment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.deployment')),
                ('terraform_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformparam')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.provider'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='terraform_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformmodule'),
        ),
    ]
