# Generated by Django 3.2.9 on 2021-12-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('apply_date', models.DateTimeField()),
                ('destroy_date', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('deletion_date', models.DateTimeField()),
                ('is_useable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TerraformParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformParamToModuleAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformmodule')),
                ('tf_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformparam')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('deployment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.deployment')),
                ('tf_param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformparam')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='tf_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timon.terraformmodule'),
        ),
    ]
