# Generated by Django 3.2.9 on 2021-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='tf_module_id',
            new_name='terraform_module_id',
        ),
        migrations.RenameField(
            model_name='deploymentparam',
            old_name='tf_param_id',
            new_name='terraform_param_id',
        ),
        migrations.RenameField(
            model_name='terraformparamtomoduleassociation',
            old_name='tf_module_id',
            new_name='terraform_module_id',
        ),
        migrations.RenameField(
            model_name='terraformparamtomoduleassociation',
            old_name='tf_param_id',
            new_name='terraform_param_id',
        ),
        migrations.AlterField(
            model_name='terraformmodule',
            name='path',
            field=models.FilePathField(),
        ),
    ]
