# Generated by Django 3.2.9 on 2021-12-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timon', '0002_auto_20211209_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workload',
        ),
    ]
