# Generated by Django 3.2.9 on 2021-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timon', '0003_delete_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformmodule',
            name='path',
            field=models.FilePathField(path='/'),
        ),
    ]
