---
- name: Build wireguard mesh
  hosts: all
  remote_user: root
  any_errors_fatal: true
  vars:
    wireguard_mask_bits: 8
    wireguard_port: 51871
  handlers:
    - name: systemd network restart
      service:
        name: systemd-networkd
        state: restarted
        enabled: true
      become: true
  tasks:
    - name: Install wireguard
      ansible.builtin.apt:
        name: wireguard
        state: present
        update_cache: true

    - name: Generate Wireguard keypair
      shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
      args:
        creates: /etc/wireguard/privatekey
      become: true

    - name: Register private key
      shell: cat /etc/wireguard/privatekey
      register: wireguard_private_key
      changed_when: false
      become: true

    - name: Register public key
      shell: cat /etc/wireguard/publickey
      register: wireguard_public_key
      changed_when: false
      become: true

    - name: Generate preshared keyskeypair
      shell: "wg genpsk > /etc/wireguard/psk-{{ item }}"
      args:
        creates: "/etc/wireguard/psk-{{ item }}"
      when: inventory_hostname < item
      with_items: "{{ groups['all'] }}"

    - name: Register preshared key
      shell: "cat /etc/wireguard/psk-{{ item }}"
      register: wireguard_preshared_key
      changed_when: false
      when: inventory_hostname < item
      with_items: "{{ groups['all'] }}"


    - name: Massege preshared keys
      set_fact: "wireguard_preshared_keys={{ wireguard_preshared_keys|default({}) | combine( {item.item: item.stdout} ) }}"
      when: item.skipped is not defined
      with_items: "{{ wireguard_preshared_key.results }}"

    - name: Setup wg0 device
      template:
        src: systemd.netdev
        dest: /etc/systemd/network/99-wg0.netdev
        owner: root
        group: systemd-network
        mode: 0640
      notify: systemd network restart

    - name: Setup wg0 network
      template:
        src: systemd.network
        dest: /etc/systemd/network/99-wg0.network
        owner: root
        group: systemd-network
        mode: 0640
      notify: systemd network restart
